In [120]:
import numpy
#import typing as tp

def matrix_multiplication(A, B):
    l = B.shape[1]
    A2 = numpy.array([A]*l)
    B2 = numpy.array([B]*l)
    B2 = numpy.stack(B2, axis = 1)
    C = numpy.sum(A2*B2.T, axis = 2).T
    return C

A = np.linspace(1, 12, 25).reshape(5,5)
B = np.linspace(2, 13, 25).reshape(5,5)
#A = np.linspace(1, 12, 12).reshape(3,4)
#B = np.linspace(2, 13, 12).reshape(4,3)
print(A)
print(B)
#print(A@B)
C = matrix_multiplication(A, B)
print(C- A@B)


[[ 1.          1.45833333  1.91666667  2.375       2.83333333]
 [ 3.29166667  3.75        4.20833333  4.66666667  5.125     ]
 [ 5.58333333  6.04166667  6.5         6.95833333  7.41666667]
 [ 7.875       8.33333333  8.79166667  9.25        9.70833333]
 [10.16666667 10.625      11.08333333 11.54166667 12.        ]]
[[ 2.          2.45833333  2.91666667  3.375       3.83333333]
 [ 4.29166667  4.75        5.20833333  5.66666667  6.125     ]
 [ 6.58333333  7.04166667  7.5         7.95833333  8.41666667]
 [ 8.875       9.33333333  9.79166667 10.25       10.70833333]
 [11.16666667 11.625      12.08333333 12.54166667 13.        ]]
[[ 0.00000000e+00  1.42108547e-14  0.00000000e+00 -1.42108547e-14
  -1.42108547e-14]
 [ 0.00000000e+00  0.00000000e+00  2.84217094e-14  0.00000000e+00
   0.00000000e+00]
 [-2.84217094e-14 -2.84217094e-14  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-5.68434189e-14  5.68434189e-14  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.0000000